import { UserRole } from '@/types';

export interface NavItem {
  label: string;
  href: string;
  icon: any; // Ionicons glyph name string
  roles: UserRole[];
}

export const NAV_ITEMS: NavItem[] = [
  {
    label: 'Dashboard',
    href: '/',
    icon: 'grid-outline',
    roles: [
      UserRole.ADMIN,
      UserRole.FINANCE,
      UserRole.DISPATCH,
      UserRole.NSM,
      UserRole.SUPER_STOCKIST,
      UserRole.RSM,
      UserRole.DISTRIBUTOR,
      UserRole.ASM,
      UserRole.SO,
      UserRole.ASE,
      UserRole.RETAILER,
    ],
  },
  {
    label: 'User Management',
    href: '/users',
    icon: 'people-outline',
    roles: [
      UserRole.ADMIN,
      UserRole.NSM,
      UserRole.RSM,
      UserRole.ASM,
      UserRole.SUPER_STOCKIST,
      UserRole.DISTRIBUTOR,
      UserRole.SO,
      UserRole.ASE,
    ],
  },
  {
    label: 'BP Transfer',
    href: '/admin/transfer-business-partner',
    icon: 'swap-horizontal-outline',
    roles: [UserRole.ADMIN],
  },
  {
    label: 'My Network',
    href: '/users',
    icon: 'people-outline',
    roles: [UserRole.RETAILER],
  },
  {
    label: 'Territories',
    href: '/territories',
    icon: 'location-outline',
    roles: [UserRole.ADMIN],
  },
  {
    label: 'SKU Catalog',
    href: '/catalog',
    icon: 'book-outline',
    roles: [UserRole.ADMIN, UserRole.SUPER_STOCKIST, UserRole.DISTRIBUTOR, UserRole.FINANCE],
  },
  {
    label: 'SKU Master',
    href: '/skus',
    icon: 'cube-outline',
    roles: [
      UserRole.SUPER_STOCKIST,
      UserRole.DISTRIBUTOR,
      UserRole.RETAILER,
    ],
  },
  {
    label: 'Inventory Intel',
    href: '/inventory-intel',
    icon: 'analytics-outline',
    roles: [UserRole.SUPER_STOCKIST, UserRole.DISTRIBUTOR, UserRole.RETAILER, UserRole.ASM, UserRole.RSM, UserRole.SO, UserRole.ASE],
  },
  {
    label: 'Stock Movements',
    href: '/stock-movements',
    icon: 'trending-up-outline',
    roles: [
      UserRole.ADMIN,
      UserRole.NSM,
      UserRole.SUPER_STOCKIST,
      UserRole.RSM,
      UserRole.DISTRIBUTOR,
      UserRole.ASM,
      UserRole.SO,
      UserRole.ASE,
      UserRole.RETAILER,
    ],
  },
  {
    label: 'Orders',
    href: '/orders',
    icon: 'cart-outline',
    roles: [
      UserRole.ADMIN,
      UserRole.FINANCE,
      UserRole.DISPATCH,
      UserRole.NSM,
      UserRole.SUPER_STOCKIST,
      UserRole.RSM,
      UserRole.DISTRIBUTOR,
      UserRole.ASM,
      UserRole.SO,
      UserRole.ASE,
      UserRole.RETAILER,
    ],
  },
  {
    label: 'My Performance',
    href: '/performance',
    icon: 'stats-chart-outline',
    roles: [UserRole.SO, UserRole.ASE],
  },
  {
    label: 'I Am Here',
    href: '/i-am-here',
    icon: 'location-outline',
    roles: [UserRole.SO, UserRole.ASE, UserRole.ASM, UserRole.RSM, UserRole.NSM],
  },
  {
    label: 'Add Retailer',
    href: '/beat-visits',
    icon: 'camera-outline',
    roles: [UserRole.SO, UserRole.ASE],
  },
  {
    label: 'Create New Beat',
    href: '/beat-visits',
    icon: 'camera-outline',
    roles: [UserRole.ASM, UserRole.RSM],
  },
  {
    label: 'Leaderboard',
    href: '/leaderboard',
    icon: 'trophy-outline',
    roles: [UserRole.ADMIN, UserRole.NSM, UserRole.RSM, UserRole.ASM, UserRole.SO, UserRole.ASE],
  },
  {
    label: 'Outlet Report',
    href: '/outlet-wise',
    icon: 'home-outline',
    roles: [UserRole.ADMIN, UserRole.NSM, UserRole.RSM, UserRole.ASM, UserRole.SO, UserRole.ASE],
  },
  {
    label: 'SKU Report',
    href: '/sku-report',
    icon: 'trending-up-outline',
    roles: [UserRole.ADMIN],
  },
  {
    label: 'Notifications',
    href: '/notifications',
    icon: 'notifications-outline',
    roles: [
      UserRole.ADMIN,
      UserRole.FINANCE,
      UserRole.DISPATCH,
      UserRole.NSM,
      UserRole.SUPER_STOCKIST,
      UserRole.RSM,
      UserRole.DISTRIBUTOR,
      UserRole.ASM,
      UserRole.SO,
      UserRole.ASE,
      UserRole.RETAILER,
    ],
  },
  {
    label: 'Attendance',
    href: '/attendance',
    icon: 'clipboard-outline',
    roles: [UserRole.RSM, UserRole.ASM, UserRole.SO, UserRole.ASE],
  },
  {
    label: 'Admin Performance',
    href: '/admin/performance',
    icon: 'stats-chart-outline',
    roles: [UserRole.ADMIN, UserRole.NSM],
  },
  {
    label: 'Team Performance',
    href: '/admin/performance',
    icon: 'stats-chart-outline',
    roles: [UserRole.RSM, UserRole.ASM, UserRole.ASE],
  },
  {
    label: 'Attendance Track',
    href: '/admin/attendance',
    icon: 'clipboard-outline',
    roles: [UserRole.ADMIN, UserRole.NSM, UserRole.RSM, UserRole.ASM],
  },
  {
    label: 'Summary',
    href: '/admin/summary',
    icon: 'list-outline',
    roles: [UserRole.ADMIN],
  },
  {
    label: 'Admin Inventory',
    href: '/admin/inventory',
    icon: 'archive-outline',
    roles: [UserRole.ADMIN],
  },
  {
    label: 'Announcements',
    href: '/announcement',
    icon: 'megaphone-outline',
    roles: [UserRole.ADMIN, UserRole.NSM, UserRole.RSM, UserRole.ASM, UserRole.SO, UserRole.ASE],
  },
  // {
  //   label: 'Role Permissions',
  //   href: '/admin/role-permissions',
  //   icon: 'shield-checkmark-outline',
  //   roles: [UserRole.ADMIN],
  // },
];
